name: Pipeline

on: push

jobs:
  code-quality:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Run pre-commit checks
        run: |
          poetry run pre-commit run -a 

  run-unit-tests:
    needs:
      - code-quality
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Run pytest
        run: |
          poetry run pytest --cov --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish-docker-image:
    needs:
      - run-unit-tests
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Get Git Commit Tag Name
        uses: olegtarasov/get-tag@v2.1.4
      - name: Set up Python environment
        uses: ./.github/actions/setup-environment
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Build and publish Images to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |          
          poetry run python publish.py
